apiVersion: v1
kind: Secret
metadata:
  name: {{ include "queryexporter.fullname" . }}
  labels:
    {{- include "queryexporter.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: |-
  {{ .Values.configuration | b64enc | nindent 4 }}
